import { IData } from './utils/interfaces';

/* eslint-disable */
const DATA: Array<IData> = [
  { text: "Where is he living,—clipp'd in with the sea that chides the banks of England, Scotland, Wales,—which calls me pupil, or hath read to me?" },
  { text: "Neró var fæddur Lucius Domitius Ahenobarbus og var eini sonur Gnaeusar Domitiusar Ahenobarbusar og Agrippinu yngri, systur Calígúla. Faðir hans var fjarskyldur ættingi Ágústusar, en Ágústus var einnig langafi móður hans." },
  { text: "Einige Freunde, von gleicher Wärme für die Wahrheit und die sittliche Schönheit beseelt, welche sich auf ganz verschiedenen Wegen in derselben Ueberzeugung vereinigt haben, und nun mit ruhigerem Blik die zurükgelegte Bahn überschauen, haben sich zu dem Entwurfe verbunden, einige Revolutionen und Epochen des Denkens, einige Ausschweifungen der grübelnden Vernunft in dem Gemählde zweier Jünglinge von ungleichen Karakteren zu entwikkeln, und in Form eines Briefwechsels der Welt vorzulegen." },
  { text: "И надо сказать, усердно исполнял он свою обязанность: на дворе у него никогда ни щепок не валялось, ни сору; застрянет ли в грязную пору где-нибудь с бочкой отданная под его начальство разбитая кляча-водовозка, он только двинет плечом — и не только телегу, самое лошадь спихнет с места; дрова ли примется он колоть, топор так и звенит у него, как стекло, и летят во все стороны осколки и поленья; а что насчет чужих, так после того, как он однажды ночью, поймав двух воров, стукнул их друг о дружку лбами, да так стукнул, что хоть в полицию их потом не води, все в околотке очень стали уважать его; даже днем проходившие, вовсе уже не мошенники, а просто незнакомые люди, при виде грозного дворника отмахивались и кричали на него, как будто он мог слышать их крики." },
  { text: "Деревня расположена на северо-западе района, примерно в 24 км северо-западнее Дмитрова, на запруженной малой речке Малиновка…" },
  { text: "Oh! Luften var sval, Stjærnerne straalede højt over Hovedet. Til begge Sider skød Straatagene Ryg som Dyr, der sover med Hovedet gemt. Nede i Gaden vankede Vægteren med sin Lygte  og lyste op ad de lukte Døre. Men ude paa den anden Side Bjælkeværket glittede Vandet, en Stjærne spejlede sig inde mellem Sivene i Graven." },
  { text: "Одзжык кыкьямыс часа уджалан лунӧн рабочӧй керліс кӧмкӧт 800 гоз. Стахановскӧя уджалікӧ, сія пондіс керны 40 секундаӧн 3 гоз. Мымда вылӧ содіс сылӧн лунся выработкаыс?" },
  { text: "Think, when we talk of horses, that you see them printing their proud hoofs i' the receiving earth." },
  { text: "Young Barnacle was in the last degree amazed and disconcerted at sight of Arthur, and had murmured involuntarily, ‘Look here! upon my soul, you know!’ before his presence of mind returned." },
  { text: "Бессилен рёв зверя перед этими воплями природы, ничтожен и голос человека, и сам человек так мал, слаб, так незаметно исчезает в мелких подробностях широкой картины! От этого, может быть, так и тяжело ему смотреть на море." },
  { text: "Let us suppose, for example, that in the greater part of employments the productive powers of labour had been improved to ten fold, or that a day's labour could produce ten times the quantity of work which it had done originally; but that in a particular employment they had been improved, only to double, or that a day's labour could produce only twice the quantity of work which it had done before." },
  { text: "«Ядреная антоновка - к веселому году». Деревенские дела хороши, если антоновка уродилась: значит и хлеб уродился... Вспоминается мне урожайный год." },
  { text: "Descend from Heav'n Urania, by that name if rightly thou art call'd, whose Voice divine following, above th' Olympian Hill I soare, above the flight of Pegasean wing." },
  { text: "Sørdomen (The Southern Dome) is an ice dome of Austfonna at Nordaustlandet, Svalbard. The glacier cap of Austfonna has two significant ice domes, Sørdomen and Norddomen further north. The part of Austfonna west of Sørdomen is called Palanderisen." },
  { text: "Este Ginés de Pasamonte, a quien don Quijote llamaba Ginesillo de Parapilla, fue el que hurtó a Sancho Panza el rucio; que, por no haberse puesto el cómo ni el cuándo en la primera parte, por culpa de los impresores, ha dado en qué entender a muchos, que atribuían a poca memoria del autor la falta de emprenta." },
  { text: "Ludovico aveva già toccata in un braccio una pugnalata d’un servitore; e il nemico gli cadeva addosso per finirlo, quando Cristoforo vedendo il suo padrone nell’estremo pericolo s’avventò col pugnale al signore, il quale rivolta tutta la sua ira contra di lui lo passò colla spada." },
  { text: "Eh bien, mon prince. Gênes et Lucques ne sont plus que des apanages, des поместья, de la famille Buonaparte. Non, je vous préviens que si vous ne me dites pas que nous avons la guerre, si vous vous permettez encore de pallier toutes les infamies, toutes les atrocités de cet Antichrist (ma parole, j’y crois) — je ne vous connais plus, vous n’êtes plus mon ami, vous n’êtes plus мой верный раб, comme vous dites. Ну, здравствуйте, здравствуйте. Je vois que je vous fais peur, садитесь и рассказывайте." },
  { text: "The stubborn and daring, though brutal courage of Front-de-Boeuf; the buoyant spirits and bold bearing of De Bracy; the sagacity, martial experience, and renowned valour of Brian de Bois-Guilbert, were important to the success of their conspiracy; and, while cursing in secret their unnecessary and unmeaning absence, neither John nor his adviser dared to proceed without them." },
  { text: "Неожиданная весть сильно меня поразила. Комендант Нижнеозерной крепости, тихий и скромный молодой человек, был мне знаком: месяца за два перед тем проезжал он из Оренбурга с молодой своей женою и останавливался у Ивана Кузмича. Нижнеозерная находилась от нашей крепости верстах в двадцати пяти. С часу на час должно было и нам ожидать нападения Пугачева. Участь Марьи Ивановны живо представилась мне, и сердце у меня так и замерло." },
  { text: "La terre, toute parfumée, reparut aux yeux des voyageurs. Le ballon, tournant sur place au milieu des courants opposés, avait à peine dérivé ; le docteur, laissant se contracter le gaz, descendit afin de saisir une direction plus septentrionale." },
];

export { DATA };
